### ISSUE TITLE
Successful? model build (output.cif written) despite run ending in error 

### ISSUE THREAD

**Issue by fjkoh** [3dem/model-angelo#22]
Hi, I have installed this on a 4xA5000 system using default "personal use" parameters as specified in the readme. Install went fine.
I tested building without sequence file provided with a 3A ribosome map and a 2.5A soluble protein map. 2.5A soluble protein map went well, while 3A ribosome map only modelled a small section of the density. In the output given during the run, no errors or warnings were given. However in the logFile, both runs ended with following error message

```
2022-11-02 at 23:47:17 | INFO | Loaded module from step: 529999
2022-11-03 at 00:04:23 | ERROR | Error in ModelAngelo
Traceback (most recent call last):

  File "/home/administrator/miniconda3/envs/model_angelo/bin/model_angelo", line 33, in <module>
    sys.exit(load_entry_point('model-angelo==0.2', 'console_scripts', 'model_angelo')())
    │   │    └ <function importlib_load_entry_point at 0x7fd5ce1aa0d0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/home/administrator/miniconda3/envs/model_angelo/lib/python3.9/site-packages/model_angelo-0.2-py3.9.egg/model_angelo/__main__.py", line 51, in main
    args.func(args)
    │    │    └ Namespace(volume_path='run_class001.mrc', output_dir='output', mask_path=None, device='cpu', config_path=None, model_bundle_n...
    │    └ <function main at 0x7fd50b2ccca0>
    └ Namespace(volume_path='run_class001.mrc', output_dir='output', mask_path=None, device='cpu', config_path=None, model_bundle_n...
> File "/home/administrator/miniconda3/envs/model_angelo/lib/python3.9/site-packages/model_angelo-0.2-py3.9.egg/model_angelo/apps/build_no_seq.py", line 230, in main
    if not parsed_args.keep_intermediate_output:
           └ Namespace(volume_path='run_class001.mrc', output_dir='output', mask_path=None, device='cpu', config_path=None, model_bundle_n...

AttributeError: 'Namespace' object has no attribute 'keep_intermediate_output'
```

I hope this is the right place to report this and I am not doing something dumb.

**Comment by jamaliki** [comment]
Uh oh sorry, I think I have introduced a bug. Let me quickly fix and let you know.

In the meantime, could you send me the command you ran for the ribosome? It should model the vast majority of the protein density, if you are seeing something else, then that is a bug.

**Comment by jamaliki** [comment]
Can you try pulling the newest commit and just running `python setup.py install`

**Comment by fjkoh** [comment]
Hi Kiarash,

Works now with no errors. Output is unaffected.

Best regards,

Koh Fujiet, Adrian

**Comment by jamaliki** [comment]
Great, but your ribosome map is still only being partially solved? If that is an issue you would like me to investigate, you could email me your map.

**Comment by fjkoh** [comment]
Hi Kiarash,

The building went better this time round and much more of the protein chain
is built. Thanks for fixing it so quickly!

Best regards,

Koh Fujiet, Adrian

**Comment by jamaliki** [comment]
Great!
