### ISSUE TITLE
ModuleNotFoundError: No module named 'model_angelo.c_alpha'

### ISSUE THREAD

**Issue by rajanprabu** [3dem/model-angelo#8]
Hi there,

I tried following the instructions, but unfortunately I get the following error. 
Traceback (most recent call last):
  File "/fs/pool/pool-schulman-soft/hpcl8/ModelAngelo/miniconda/envs/model_angelo/bin/model_angelo", line 33, in <module>
    sys.exit(load_entry_point('model-angelo==0.0.1', 'console_scripts', 'model_angelo')())
  File "/fs/pool/pool-schulman-soft/hpcl8/ModelAngelo/miniconda/envs/model_angelo/lib/python3.9/site-packages/model_angelo-0.0.1-py3.9.egg/model_angelo/__main__.py", line 23, in main
  File "<frozen zipimport>", line 259, in load_module
  File "/fs/pool/pool-schulman-soft/hpcl8/ModelAngelo/miniconda/envs/model_angelo/lib/python3.9/site-packages/model_angelo-0.0.1-py3.9.egg/model_angelo/apps/build.py", line 18, in <module>
ModuleNotFoundError: No module named 'model_angelo.c_alpha'

It is trying to look for folders after the egg file thats confusing..

**Comment by jamaliki** [comment]
Hi, thank you for trying ModelAngelo.

This is a bug that I may have introduced in the morning. Can you please pull the newest version of the code and run the install script again?

**Comment by rajanprabu** [comment]
Yes that worked. Thanks @jamaliki
